### ISSUE TITLE
Milestone 4 Checklist

### ISSUE THREAD

**Issue by Palisand** [Palisand/Circum#22]
Check off when in **master**:
- [x] Better levels
- [ ] Gauge difficulty
- [x] SOUNDS: tether, ricochet, release, background, ~~master orb capture~~
- [x] Experimental player-orb attraction
- [x] Restart current level (save orb configuration)
- [x] Level advance
- [x] Tutorial Levels
- [x] Payloads release captured orbs for a limited time
- [x] Payloads guard void orbs for a limited time
- [x] Clean code so it only handles single player
- [x] Optimization
- [x] Full trail fix
- [x] Can tether to anything
- [x] Hammer on any tether

Menu? (probably next milestone)
