### ISSUE TITLE
Milestone 5 Checklist

### ISSUE THREAD

**Issue by Palisand** [Palisand/Circum#31]
- [x] No more anti-theme levels (should not be challenging)
- [x] Starter menu
- [x] Different / Oscillating tether sound? (irritating to few)
- [x] Key orb capture sound
- [x] Payload impact sound
- [x] Make tethering and orbiting easier to distinguish
- [x] Reusable key orbs
- [x] Make it easier to capture the last orbs (by slowing / stopping all orbs)
- [x] Tutorials should progress better
- [x] Tutorial level to ensure players understand launch direction
- [x] Smaller void orb collision
- [x] Distinguish payloads from player
- [x] Consistent orb color
- [x] Increase orb attraction
- [x] Master orb attraction
- [x] Increase release time
