### ISSUE TITLE
SFX Checklist

### ISSUE THREAD

**Issue by Palisand** [Palisand/Circum#4]
- [ ] Launch
- [ ] Player-On-Orb Collision
- [ ] Player-On-Player Collision
- [ ] Ricochet
- [ ] Wall bounce
- [ ] Player death via Void Orb
- [ ] Orb Capture
- [ ] Orb Release
- [ ] Orb Destruction
- [ ] Streak activation: Possession
- [ ] Streak activation: Domination

**Comment by Palisand** [comment]
Not used
