### ISSUE TITLE
Final Milestone (aka "Shit We Gotta Do")

### ISSUE THREAD

**Issue by Palisand** [Palisand/Circum#51]
- [x] Launch indicator and/or directional change (w/ toggle option)
- [x] Orb size variety
- [x] Different fixed-orbit origins
- [x] Level Progression Changes
  - [x] Variety before difficulty
  - [x] Most (preferably all) levels should have a purpose
- [x] Separate random play 
- [x] Presentation
  - [x] What is the player's objective?
  - [x] Why do players care?
